2 add readme
AllenNeuralDynamics/aind-multiplane-ophys-pipeline pull request #3
Opened 2024-09-17 23:27 UTC by arielleleon

2024-09-17 23:41 UTC, dyf requested changes

2024-09-17 23:41 UTC, dyf commented on README.md
> +# aind-multiplane-ophys-pipeline
can probably remove

2024-09-17 23:41 UTC, dyf commented on README.md
> +The multiplane-ophys pipeline is a processing pipeline which uses [Suite2p](https://github.com/MouseLand/suite2p) for both motion correction and segmentation. The final outputs of the pipeline are RO
I would emphasize that this is for data in which multiple planar fields of view are collected simultaneously and maybe link to the mesoscope docs.

2024-09-17 23:41 UTC, dyf commented on README.md
> +The multiplane-ophys pipeline is a processing pipeline which uses [Suite2p](https://github.com/MouseLand/suite2p) for both motion correction and segmentation. The final outputs of the pipeline are RO
You could also link to the single-plane pipeline here.

2024-09-17 23:41 UTC, dyf commented on README.md
> +* Extraction (HDF5): Datasets include:
`extraction.h5`: HDF5 file including:

2024-09-17 23:41 UTC, dyf commented on README.md
> +The following folders will be under the field of view directory within the `results` folder:
you could make this look like this: 
![image](https://github.com/user-attachments/assets/aec689c1-f14b-4a3f-a4fa-a27fd5735e48)

2024-09-18 19:10 UTC, dyf requested changes

2024-09-18 19:10 UTC, dyf commented on README.md
> +The following folders will be under the field of view directory within the `results` folder:
small request: add another emoji-based folder display here that shows what the top level folders are

2024-09-18 19:10 UTC, dyf commented on README.md
> +The following folders will be under the field of view directory within the `results` folder:
kind of like an index of the below folder descriptions.

2024-09-18 19:40 UTC, j-friedrich reviewed
Figure 1:
Error in Tiff structure for upper panel: the second-last Page is 2N-1, the last one 2N.

Motion Correction:
anatomical_region_registered.h5 is listed twice as output of motion_correction.

Extraction:
The extraction.h5 outputs now much more info, almost too much, see its [README](https://github.com/AllenNeuralDynamics/aind-ophys-extraction-suite2p)

2024-09-18 22:49 UTC, merged